# Jekyll configuration
# This file ensures Jekyll is disabled
auto: false
include: []
plugins: []

# GitHub Pages settings
repository: zarigata/website
branch: gh-pages

# Build settings
timezone: America/Argentina/Buenos_Aires

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/
#   - README.md
