# CODEX CONFIGURATION: Site Core
title: CatchyCompany
baseurl: /
lang: en

# Internationalization
languages: ["en", "ar"]

# Design System
pastel_palette:
  primary: "#B2EBF2"
  secondary: "#F8BBD0"
  accent: "#DCE775"
  background: "#FFFDE7"

plugins:
  - jekyll-polyglot

# GitHub Pages Compliance
github:
  branch: main
  repository: catchycompany/web
